name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: ['0.14.1', '0.15.1']

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        # Pure Zig implementation - no external dependencies required
        echo "Using pure Zig implementation with zero external dependencies"

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}

    - name: Verify Zig installation
      run: zig version

    - name: Build project
      run: zig build

    - name: Run build tests
      run: zig build test
